// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// podcastDao is the data access object for the table hg_podcast.
// You can define custom methods on it to extend its functionality as needed.
type podcastDao struct {
	*internal.PodcastDao
}

var (
	// Podcast is a globally accessible object for table hg_podcast operations.
	Podcast = podcastDao{internal.NewPodcastDao()}
)

// Add your custom methods and functionality below.
